# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.3.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractScrollArea, QApplication, QDialog, QFrame,
    QHeaderView, QLCDNumber, QLabel, QLineEdit,
    QPlainTextEdit, QPushButton, QSizePolicy, QTabWidget,
    QTableWidget, QTableWidgetItem, QTextBrowser, QVBoxLayout,
    QWidget)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(890, 627)
        self.tabPedidos = QTabWidget(Dialog)
        self.tabPedidos.setObjectName(u"tabPedidos")
        self.tabPedidos.setGeometry(QRect(0, 0, 861, 621))
        self.tabPedidos.setFocusPolicy(Qt.StrongFocus)
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.EditarEmpleado = QTabWidget(self.tab)
        self.EditarEmpleado.setObjectName(u"EditarEmpleado")
        self.EditarEmpleado.setGeometry(QRect(-10, 0, 831, 501))
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.lineeditRollempleado = QLineEdit(self.tab_3)
        self.lineeditRollempleado.setObjectName(u"lineeditRollempleado")
        self.lineeditRollempleado.setGeometry(QRect(30, 170, 113, 20))
        self.lineeditCURPempleado = QLineEdit(self.tab_3)
        self.lineeditCURPempleado.setObjectName(u"lineeditCURPempleado")
        self.lineeditCURPempleado.setGeometry(QRect(30, 220, 231, 20))
        self.lineeditNombreempleado = QLineEdit(self.tab_3)
        self.lineeditNombreempleado.setObjectName(u"lineeditNombreempleado")
        self.lineeditNombreempleado.setGeometry(QRect(30, 110, 431, 20))
        self.lineeditRFCempleado = QLineEdit(self.tab_3)
        self.lineeditRFCempleado.setObjectName(u"lineeditRFCempleado")
        self.lineeditRFCempleado.setGeometry(QRect(30, 270, 231, 20))
        self.lineeditDireccionempleado = QLineEdit(self.tab_3)
        self.lineeditDireccionempleado.setObjectName(u"lineeditDireccionempleado")
        self.lineeditDireccionempleado.setGeometry(QRect(30, 320, 441, 20))
        self.label_2 = QLabel(self.tab_3)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(30, 90, 111, 16))
        self.label_4 = QLabel(self.tab_3)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(30, 150, 47, 13))
        self.label_5 = QLabel(self.tab_3)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(30, 200, 47, 13))
        self.label_6 = QLabel(self.tab_3)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(30, 250, 47, 13))
        self.label_7 = QLabel(self.tab_3)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(30, 300, 81, 16))
        self.label_8 = QLabel(self.tab_3)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(30, 350, 51, 20))
        self.lineeditTELEmpleado7 = QLineEdit(self.tab_3)
        self.lineeditTELEmpleado7.setObjectName(u"lineeditTELEmpleado7")
        self.lineeditTELEmpleado7.setGeometry(QRect(30, 380, 181, 20))
        self.pushButton = QPushButton(self.tab_3)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(510, 430, 75, 23))
        self.pushButton_2 = QPushButton(self.tab_3)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(620, 430, 75, 23))
        self.label_36 = QLabel(self.tab_3)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(490, 110, 281, 211))
        self.label_36.setPixmap(QPixmap(u"L3.png"))
        self.EditarEmpleado.addTab(self.tab_3, "")
        self.tab_10 = QWidget()
        self.tab_10.setObjectName(u"tab_10")
        self.mostrar_all_empleados = QPushButton(self.tab_10)
        self.mostrar_all_empleados.setObjectName(u"mostrar_all_empleados")
        self.mostrar_all_empleados.setGeometry(QRect(550, 372, 91, 51))
        self.tableEmpleado = QTableWidget(self.tab_10)
        if (self.tableEmpleado.columnCount() < 7):
            self.tableEmpleado.setColumnCount(7)
        __qtablewidgetitem = QTableWidgetItem()
        self.tableEmpleado.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.tableEmpleado.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.tableEmpleado.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.tableEmpleado.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.tableEmpleado.setHorizontalHeaderItem(4, __qtablewidgetitem4)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.tableEmpleado.setHorizontalHeaderItem(5, __qtablewidgetitem5)
        __qtablewidgetitem6 = QTableWidgetItem()
        self.tableEmpleado.setHorizontalHeaderItem(6, __qtablewidgetitem6)
        self.tableEmpleado.setObjectName(u"tableEmpleado")
        self.tableEmpleado.setGeometry(QRect(10, 30, 721, 301))
        self.tableEmpleado.horizontalHeader().setDefaultSectionSize(150)
        self.EditarEmpleado.addTab(self.tab_10, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.lineEdit_IDEMPLEADOEDIT = QLineEdit(self.tab_4)
        self.lineEdit_IDEMPLEADOEDIT.setObjectName(u"lineEdit_IDEMPLEADOEDIT")
        self.lineEdit_IDEMPLEADOEDIT.setGeometry(QRect(60, 80, 113, 22))
        self.lineEdit_EDITEMPLEADO = QLineEdit(self.tab_4)
        self.lineEdit_EDITEMPLEADO.setObjectName(u"lineEdit_EDITEMPLEADO")
        self.lineEdit_EDITEMPLEADO.setGeometry(QRect(270, 30, 441, 21))
        self.lineEdit_EDITROLL = QLineEdit(self.tab_4)
        self.lineEdit_EDITROLL.setObjectName(u"lineEdit_EDITROLL")
        self.lineEdit_EDITROLL.setGeometry(QRect(270, 70, 161, 21))
        self.lineEdit_EDITCURP = QLineEdit(self.tab_4)
        self.lineEdit_EDITCURP.setObjectName(u"lineEdit_EDITCURP")
        self.lineEdit_EDITCURP.setGeometry(QRect(270, 110, 201, 21))
        self.lineEdit_EDITRFC = QLineEdit(self.tab_4)
        self.lineEdit_EDITRFC.setObjectName(u"lineEdit_EDITRFC")
        self.lineEdit_EDITRFC.setGeometry(QRect(270, 150, 201, 21))
        self.lineEdit_EDITDOMIC = QLineEdit(self.tab_4)
        self.lineEdit_EDITDOMIC.setObjectName(u"lineEdit_EDITDOMIC")
        self.lineEdit_EDITDOMIC.setGeometry(QRect(270, 190, 441, 21))
        self.lineEdit_EDITTEL = QLineEdit(self.tab_4)
        self.lineEdit_EDITTEL.setObjectName(u"lineEdit_EDITTEL")
        self.lineEdit_EDITTEL.setGeometry(QRect(270, 230, 171, 21))
        self.label_3 = QLabel(self.tab_4)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(60, 50, 101, 16))
        self.label_9 = QLabel(self.tab_4)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(270, 10, 111, 16))
        self.label_10 = QLabel(self.tab_4)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(270, 50, 71, 16))
        self.label_11 = QLabel(self.tab_4)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(270, 90, 49, 16))
        self.label_12 = QLabel(self.tab_4)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(270, 130, 49, 16))
        self.label_13 = QLabel(self.tab_4)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(270, 170, 71, 16))
        self.label_14 = QLabel(self.tab_4)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(270, 210, 49, 16))
        self.mostrar_edit = QPushButton(self.tab_4)
        self.mostrar_edit.setObjectName(u"mostrar_edit")
        self.mostrar_edit.setGeometry(QRect(20, 120, 111, 21))
        self.ActualizarEmp = QPushButton(self.tab_4)
        self.ActualizarEmp.setObjectName(u"ActualizarEmp")
        self.ActualizarEmp.setGeometry(QRect(140, 120, 71, 21))
        self.pushbutton_EliminarEm = QPushButton(self.tab_4)
        self.pushbutton_EliminarEm.setObjectName(u"pushbutton_EliminarEm")
        self.pushbutton_EliminarEm.setGeometry(QRect(44, 170, 121, 24))
        self.plainTextEdit = QPlainTextEdit(self.tab_4)
        self.plainTextEdit.setObjectName(u"plainTextEdit")
        self.plainTextEdit.setGeometry(QRect(20, 250, 231, 201))
        self.label_37 = QLabel(self.tab_4)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(320, 260, 281, 211))
        self.label_37.setPixmap(QPixmap(u"L3.png"))
        self.EditarEmpleado.addTab(self.tab_4, "")
        self.tabPedidos.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.Mostrar = QTabWidget(self.tab_2)
        self.Mostrar.setObjectName(u"Mostrar")
        self.Mostrar.setGeometry(QRect(0, 0, 781, 511))
        self.tab_12 = QWidget()
        self.tab_12.setObjectName(u"tab_12")
        self.label_16 = QLabel(self.tab_12)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(9, 113, 171, 16))
        self.nombre_prov = QLineEdit(self.tab_12)
        self.nombre_prov.setObjectName(u"nombre_prov")
        self.nombre_prov.setGeometry(QRect(10, 140, 291, 21))
        self.label_17 = QLabel(self.tab_12)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(10, 170, 151, 16))
        self.telefono_prov = QLineEdit(self.tab_12)
        self.telefono_prov.setObjectName(u"telefono_prov")
        self.telefono_prov.setGeometry(QRect(10, 200, 133, 20))
        self.label_20 = QLabel(self.tab_12)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(10, 230, 43, 16))
        self.dire_prov = QLineEdit(self.tab_12)
        self.dire_prov.setObjectName(u"dire_prov")
        self.dire_prov.setGeometry(QRect(10, 260, 391, 21))
        self.agregar_prov = QPushButton(self.tab_12)
        self.agregar_prov.setObjectName(u"agregar_prov")
        self.agregar_prov.setGeometry(QRect(9, 424, 75, 23))
        self.pushButton_6 = QPushButton(self.tab_12)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(9, 453, 75, 23))
        self.label_35 = QLabel(self.tab_12)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(450, 30, 281, 211))
        self.label_35.setPixmap(QPixmap(u"L3.png"))
        self.Mostrar.addTab(self.tab_12, "")
        self.tab_13 = QWidget()
        self.tab_13.setObjectName(u"tab_13")
        self.mostrar_all_prov_3 = QPushButton(self.tab_13)
        self.mostrar_all_prov_3.setObjectName(u"mostrar_all_prov_3")
        self.mostrar_all_prov_3.setGeometry(QRect(514, 382, 111, 41))
        self.Mostrar_table_prov = QTableWidget(self.tab_13)
        if (self.Mostrar_table_prov.columnCount() < 4):
            self.Mostrar_table_prov.setColumnCount(4)
        __qtablewidgetitem7 = QTableWidgetItem()
        self.Mostrar_table_prov.setHorizontalHeaderItem(0, __qtablewidgetitem7)
        __qtablewidgetitem8 = QTableWidgetItem()
        self.Mostrar_table_prov.setHorizontalHeaderItem(1, __qtablewidgetitem8)
        __qtablewidgetitem9 = QTableWidgetItem()
        self.Mostrar_table_prov.setHorizontalHeaderItem(2, __qtablewidgetitem9)
        __qtablewidgetitem10 = QTableWidgetItem()
        self.Mostrar_table_prov.setHorizontalHeaderItem(3, __qtablewidgetitem10)
        self.Mostrar_table_prov.setObjectName(u"Mostrar_table_prov")
        self.Mostrar_table_prov.setGeometry(QRect(60, 70, 641, 251))
        self.Mostrar_table_prov.horizontalHeader().setDefaultSectionSize(160)
        self.Mostrar.addTab(self.tab_13, "")
        self.tab_11 = QWidget()
        self.tab_11.setObjectName(u"tab_11")
        self.label_18 = QLabel(self.tab_11)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(40, 50, 81, 16))
        self.lineEdit_edit_prov = QLineEdit(self.tab_11)
        self.lineEdit_edit_prov.setObjectName(u"lineEdit_edit_prov")
        self.lineEdit_edit_prov.setGeometry(QRect(40, 80, 171, 20))
        self.lineEdit_2 = QLineEdit(self.tab_11)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(280, 70, 351, 20))
        self.lineEdit_3 = QLineEdit(self.tab_11)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(280, 120, 351, 20))
        self.lineEdit_4 = QLineEdit(self.tab_11)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setGeometry(QRect(280, 180, 351, 20))
        self.plainTextEdit_2 = QPlainTextEdit(self.tab_11)
        self.plainTextEdit_2.setObjectName(u"plainTextEdit_2")
        self.plainTextEdit_2.setGeometry(QRect(20, 260, 351, 161))
        self.mostrar_prov = QPushButton(self.tab_11)
        self.mostrar_prov.setObjectName(u"mostrar_prov")
        self.mostrar_prov.setGeometry(QRect(10, 130, 121, 23))
        self.actualizar_prov = QPushButton(self.tab_11)
        self.actualizar_prov.setObjectName(u"actualizar_prov")
        self.actualizar_prov.setGeometry(QRect(80, 190, 91, 23))
        self.eliminar_prov = QPushButton(self.tab_11)
        self.eliminar_prov.setObjectName(u"eliminar_prov")
        self.eliminar_prov.setGeometry(QRect(150, 130, 101, 23))
        self.label_19 = QLabel(self.tab_11)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(280, 50, 47, 13))
        self.label_21 = QLabel(self.tab_11)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(280, 100, 47, 13))
        self.label_25 = QLabel(self.tab_11)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(280, 160, 47, 13))
        self.label_38 = QLabel(self.tab_11)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(450, 240, 281, 211))
        self.label_38.setPixmap(QPixmap(u"L3.png"))
        self.Mostrar.addTab(self.tab_11, "")
        self.tabPedidos.addTab(self.tab_2, "")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.AgregarEmpleado_3 = QTabWidget(self.tab_5)
        self.AgregarEmpleado_3.setObjectName(u"AgregarEmpleado_3")
        self.AgregarEmpleado_3.setGeometry(QRect(0, 0, 741, 481))
        self.tab_14 = QWidget()
        self.tab_14.setObjectName(u"tab_14")
        self.label_23 = QLabel(self.tab_14)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(9, 105, 96, 16))
        self.nombre_ing = QLineEdit(self.tab_14)
        self.nombre_ing.setObjectName(u"nombre_ing")
        self.nombre_ing.setGeometry(QRect(10, 130, 133, 20))
        self.label_24 = QLabel(self.tab_14)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(10, 160, 63, 16))
        self.id_prov_ingg = QLineEdit(self.tab_14)
        self.id_prov_ingg.setObjectName(u"id_prov_ingg")
        self.id_prov_ingg.setGeometry(QRect(10, 180, 133, 20))
        self.label_28 = QLabel(self.tab_14)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(10, 220, 62, 16))
        self.cant_ing = QLineEdit(self.tab_14)
        self.cant_ing.setObjectName(u"cant_ing")
        self.cant_ing.setGeometry(QRect(10, 240, 133, 20))
        self.add_ing = QPushButton(self.tab_14)
        self.add_ing.setObjectName(u"add_ing")
        self.add_ing.setGeometry(QRect(10, 340, 75, 23))
        self.pushButton_8 = QPushButton(self.tab_14)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(90, 340, 75, 23))
        self.label_39 = QLabel(self.tab_14)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(340, 10, 281, 211))
        self.label_39.setPixmap(QPixmap(u"L3.png"))
        self.Mostrar_table_prov_3 = QTableWidget(self.tab_14)
        if (self.Mostrar_table_prov_3.columnCount() < 2):
            self.Mostrar_table_prov_3.setColumnCount(2)
        __qtablewidgetitem11 = QTableWidgetItem()
        self.Mostrar_table_prov_3.setHorizontalHeaderItem(0, __qtablewidgetitem11)
        __qtablewidgetitem12 = QTableWidgetItem()
        self.Mostrar_table_prov_3.setHorizontalHeaderItem(1, __qtablewidgetitem12)
        self.Mostrar_table_prov_3.setObjectName(u"Mostrar_table_prov_3")
        self.Mostrar_table_prov_3.setGeometry(QRect(230, 230, 501, 211))
        self.Mostrar_table_prov_3.horizontalHeader().setDefaultSectionSize(249)
        self.AgregarEmpleado_3.addTab(self.tab_14, "")
        self.tab_15 = QWidget()
        self.tab_15.setObjectName(u"tab_15")
        self.mostrar_all_Ing_4 = QPushButton(self.tab_15)
        self.mostrar_all_Ing_4.setObjectName(u"mostrar_all_Ing_4")
        self.mostrar_all_Ing_4.setGeometry(QRect(550, 400, 101, 41))
        self.tabl_Ing = QTableWidget(self.tab_15)
        if (self.tabl_Ing.columnCount() < 4):
            self.tabl_Ing.setColumnCount(4)
        __qtablewidgetitem13 = QTableWidgetItem()
        self.tabl_Ing.setHorizontalHeaderItem(0, __qtablewidgetitem13)
        __qtablewidgetitem14 = QTableWidgetItem()
        self.tabl_Ing.setHorizontalHeaderItem(1, __qtablewidgetitem14)
        __qtablewidgetitem15 = QTableWidgetItem()
        self.tabl_Ing.setHorizontalHeaderItem(2, __qtablewidgetitem15)
        font = QFont()
        font.setPointSize(8)
        __qtablewidgetitem16 = QTableWidgetItem()
        __qtablewidgetitem16.setFont(font);
        self.tabl_Ing.setHorizontalHeaderItem(3, __qtablewidgetitem16)
        self.tabl_Ing.setObjectName(u"tabl_Ing")
        self.tabl_Ing.setGeometry(QRect(30, 50, 641, 251))
        self.tabl_Ing.horizontalHeader().setDefaultSectionSize(160)
        self.AgregarEmpleado_3.addTab(self.tab_15, "")
        self.tab_16 = QWidget()
        self.tab_16.setObjectName(u"tab_16")
        self.label_26 = QLabel(self.tab_16)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(50, 90, 81, 16))
        self.id_ingrediente_edit = QLineEdit(self.tab_16)
        self.id_ingrediente_edit.setObjectName(u"id_ingrediente_edit")
        self.id_ingrediente_edit.setGeometry(QRect(40, 120, 121, 20))
        self.nombre_ingrediente_edit = QLineEdit(self.tab_16)
        self.nombre_ingrediente_edit.setObjectName(u"nombre_ingrediente_edit")
        self.nombre_ingrediente_edit.setGeometry(QRect(300, 60, 301, 20))
        self.label_27 = QLabel(self.tab_16)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(300, 30, 47, 13))
        self.edit_text_ing = QTextBrowser(self.tab_16)
        self.edit_text_ing.setObjectName(u"edit_text_ing")
        self.edit_text_ing.setGeometry(QRect(320, 240, 301, 192))
        self.mostrar_ing_edit = QPushButton(self.tab_16)
        self.mostrar_ing_edit.setObjectName(u"mostrar_ing_edit")
        self.mostrar_ing_edit.setGeometry(QRect(0, 150, 111, 23))
        self.eliminar_ing_edit = QPushButton(self.tab_16)
        self.eliminar_ing_edit.setObjectName(u"eliminar_ing_edit")
        self.eliminar_ing_edit.setGeometry(QRect(130, 150, 75, 23))
        self.actualizar_ing_edit = QPushButton(self.tab_16)
        self.actualizar_ing_edit.setObjectName(u"actualizar_ing_edit")
        self.actualizar_ing_edit.setGeometry(QRect(60, 190, 75, 23))
        self.nombre_ingrediente_edit_2 = QLineEdit(self.tab_16)
        self.nombre_ingrediente_edit_2.setObjectName(u"nombre_ingrediente_edit_2")
        self.nombre_ingrediente_edit_2.setGeometry(QRect(300, 120, 301, 20))
        self.nombre_ingrediente_edit_3 = QLineEdit(self.tab_16)
        self.nombre_ingrediente_edit_3.setObjectName(u"nombre_ingrediente_edit_3")
        self.nombre_ingrediente_edit_3.setGeometry(QRect(300, 170, 301, 20))
        self.label_29 = QLabel(self.tab_16)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(300, 150, 47, 13))
        self.label_30 = QLabel(self.tab_16)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(300, 100, 47, 16))
        self.label_40 = QLabel(self.tab_16)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(10, 220, 281, 211))
        self.label_40.setPixmap(QPixmap(u"L3.png"))
        self.AgregarEmpleado_3.addTab(self.tab_16, "")
        self.tabPedidos.addTab(self.tab_5, "")
        self.tab_9 = QWidget()
        self.tab_9.setObjectName(u"tab_9")
        self.label_45 = QLabel(self.tab_9)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(450, 130, 301, 321))
        self.label_45.setPixmap(QPixmap(u"L3.png"))
        self.pushButton_7 = QPushButton(self.tab_9)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(10, 250, 75, 23))
        self.pushButton_9 = QPushButton(self.tab_9)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setGeometry(QRect(10, 320, 101, 21))
        self.label_94 = QLabel(self.tab_9)
        self.label_94.setObjectName(u"label_94")
        self.label_94.setGeometry(QRect(20, 70, 81, 16))
        self.lineEdit_19 = QLineEdit(self.tab_9)
        self.lineEdit_19.setObjectName(u"lineEdit_19")
        self.lineEdit_19.setGeometry(QRect(10, 100, 113, 20))
        self.label_95 = QLabel(self.tab_9)
        self.label_95.setObjectName(u"label_95")
        self.label_95.setGeometry(QRect(10, 150, 101, 16))
        self.lineEdit_20 = QLineEdit(self.tab_9)
        self.lineEdit_20.setObjectName(u"lineEdit_20")
        self.lineEdit_20.setGeometry(QRect(10, 170, 113, 20))
        self.label_15 = QLabel(self.tab_9)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(270, 80, 281, 16))
        self.label_15.setStyleSheet(u"font: 14pt \"Calculator\";")
        self.label_96 = QLabel(self.tab_9)
        self.label_96.setObjectName(u"label_96")
        self.label_96.setGeometry(QRect(270, 50, 81, 16))
        self.id_pedido_2 = QLCDNumber(self.tab_9)
        self.id_pedido_2.setObjectName(u"id_pedido_2")
        self.id_pedido_2.setGeometry(QRect(20, 30, 71, 31))
        self.label_97 = QLabel(self.tab_9)
        self.label_97.setObjectName(u"label_97")
        self.label_97.setGeometry(QRect(20, 10, 81, 16))
        self.tabPedidos.addTab(self.tab_9, "")
        self.tab_7 = QWidget()
        self.tab_7.setObjectName(u"tab_7")
        self.table_menu = QTableWidget(self.tab_7)
        if (self.table_menu.columnCount() < 4):
            self.table_menu.setColumnCount(4)
        __qtablewidgetitem17 = QTableWidgetItem()
        self.table_menu.setHorizontalHeaderItem(0, __qtablewidgetitem17)
        __qtablewidgetitem18 = QTableWidgetItem()
        self.table_menu.setHorizontalHeaderItem(1, __qtablewidgetitem18)
        __qtablewidgetitem19 = QTableWidgetItem()
        self.table_menu.setHorizontalHeaderItem(2, __qtablewidgetitem19)
        __qtablewidgetitem20 = QTableWidgetItem()
        self.table_menu.setHorizontalHeaderItem(3, __qtablewidgetitem20)
        self.table_menu.setObjectName(u"table_menu")
        self.table_menu.setGeometry(QRect(210, 10, 581, 431))
        self.table_menu.horizontalHeader().setDefaultSectionSize(144)
        self.pushButton_4 = QPushButton(self.tab_7)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(684, 490, 91, 23))
        self.nom_producto = QLineEdit(self.tab_7)
        self.nom_producto.setObjectName(u"nom_producto")
        self.nom_producto.setGeometry(QRect(20, 80, 113, 20))
        self.lineEdit_5 = QLineEdit(self.tab_7)
        self.lineEdit_5.setObjectName(u"lineEdit_5")
        self.lineEdit_5.setGeometry(QRect(20, 130, 151, 20))
        self.lineEdit_6 = QLineEdit(self.tab_7)
        self.lineEdit_6.setObjectName(u"lineEdit_6")
        self.lineEdit_6.setGeometry(QRect(20, 180, 71, 20))
        self.label_42 = QLabel(self.tab_7)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(20, 60, 101, 16))
        self.label_43 = QLabel(self.tab_7)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(20, 110, 81, 16))
        self.label_44 = QLabel(self.tab_7)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(20, 160, 47, 13))
        self.Crear_receta = QPushButton(self.tab_7)
        self.Crear_receta.setObjectName(u"Crear_receta")
        self.Crear_receta.setGeometry(QRect(50, 300, 91, 23))
        self.Crear_receta_2 = QPushButton(self.tab_7)
        self.Crear_receta_2.setObjectName(u"Crear_receta_2")
        self.Crear_receta_2.setGeometry(QRect(50, 340, 91, 23))
        self.Crear_receta_3 = QPushButton(self.tab_7)
        self.Crear_receta_3.setObjectName(u"Crear_receta_3")
        self.Crear_receta_3.setGeometry(QRect(50, 260, 91, 23))
        self.tabPedidos.addTab(self.tab_7, "")
        self.tab_17 = QWidget()
        self.tab_17.setObjectName(u"tab_17")
        self.tabWidget = QTabWidget(self.tab_17)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 791, 511))
        self.tab_18 = QWidget()
        self.tab_18.setObjectName(u"tab_18")
        self.label_32 = QLabel(self.tab_18)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(40, 80, 71, 16))
        self.label_33 = QLabel(self.tab_18)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(40, 150, 81, 16))
        self.id_proveedor = QLineEdit(self.tab_18)
        self.id_proveedor.setObjectName(u"id_proveedor")
        self.id_proveedor.setGeometry(QRect(40, 170, 113, 20))
        self.crear_P = QPushButton(self.tab_18)
        self.crear_P.setObjectName(u"crear_P")
        self.crear_P.setGeometry(QRect(40, 310, 91, 31))
        self.id_proveedor_2 = QLineEdit(self.tab_18)
        self.id_proveedor_2.setObjectName(u"id_proveedor_2")
        self.id_proveedor_2.setGeometry(QRect(40, 230, 113, 20))
        self.label_34 = QLabel(self.tab_18)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(40, 210, 81, 16))
        self.label_41 = QLabel(self.tab_18)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(330, 0, 281, 211))
        self.label_41.setPixmap(QPixmap(u"L3.png"))
        self.pushButton_3 = QPushButton(self.tab_18)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(480, 450, 121, 23))
        self.Mostrar_table_prov_2 = QTableWidget(self.tab_18)
        if (self.Mostrar_table_prov_2.columnCount() < 2):
            self.Mostrar_table_prov_2.setColumnCount(2)
        __qtablewidgetitem21 = QTableWidgetItem()
        self.Mostrar_table_prov_2.setHorizontalHeaderItem(0, __qtablewidgetitem21)
        __qtablewidgetitem22 = QTableWidgetItem()
        self.Mostrar_table_prov_2.setHorizontalHeaderItem(1, __qtablewidgetitem22)
        self.Mostrar_table_prov_2.setObjectName(u"Mostrar_table_prov_2")
        self.Mostrar_table_prov_2.setGeometry(QRect(260, 220, 501, 211))
        self.Mostrar_table_prov_2.horizontalHeader().setDefaultSectionSize(249)
        self.label = QLabel(self.tab_18)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(40, 110, 281, 16))
        self.label.setStyleSheet(u"font: 14pt \"Calculator\";")
        self.label_46 = QLabel(self.tab_18)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(40, 10, 71, 16))
        self.id_pedido = QLCDNumber(self.tab_18)
        self.id_pedido.setObjectName(u"id_pedido")
        self.id_pedido.setGeometry(QRect(40, 30, 71, 31))
        self.tabWidget.addTab(self.tab_18, "")
        self.tab_32 = QWidget()
        self.tab_32.setObjectName(u"tab_32")
        self.MostrarPedido_button = QPushButton(self.tab_32)
        self.MostrarPedido_button.setObjectName(u"MostrarPedido_button")
        self.MostrarPedido_button.setGeometry(QRect(200, 380, 101, 31))
        self.label_67 = QLabel(self.tab_32)
        self.label_67.setObjectName(u"label_67")
        self.label_67.setGeometry(QRect(40, 360, 71, 16))
        self.ID_pedido_All = QLineEdit(self.tab_32)
        self.ID_pedido_All.setObjectName(u"ID_pedido_All")
        self.ID_pedido_All.setGeometry(QRect(40, 390, 131, 20))
        self.tab_Pedido = QTableWidget(self.tab_32)
        if (self.tab_Pedido.columnCount() < 5):
            self.tab_Pedido.setColumnCount(5)
        __qtablewidgetitem23 = QTableWidgetItem()
        self.tab_Pedido.setHorizontalHeaderItem(0, __qtablewidgetitem23)
        __qtablewidgetitem24 = QTableWidgetItem()
        self.tab_Pedido.setHorizontalHeaderItem(1, __qtablewidgetitem24)
        __qtablewidgetitem25 = QTableWidgetItem()
        self.tab_Pedido.setHorizontalHeaderItem(2, __qtablewidgetitem25)
        __qtablewidgetitem26 = QTableWidgetItem()
        self.tab_Pedido.setHorizontalHeaderItem(3, __qtablewidgetitem26)
        __qtablewidgetitem27 = QTableWidgetItem()
        __qtablewidgetitem27.setTextAlignment(Qt.AlignCenter);
        self.tab_Pedido.setHorizontalHeaderItem(4, __qtablewidgetitem27)
        self.tab_Pedido.setObjectName(u"tab_Pedido")
        self.tab_Pedido.setGeometry(QRect(20, 30, 751, 321))
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_Pedido.sizePolicy().hasHeightForWidth())
        self.tab_Pedido.setSizePolicy(sizePolicy)
        self.tab_Pedido.setFrameShape(QFrame.Box)
        self.tab_Pedido.setFrameShadow(QFrame.Sunken)
        self.tab_Pedido.setSizeAdjustPolicy(QAbstractScrollArea.AdjustIgnored)
        self.tab_Pedido.setGridStyle(Qt.SolidLine)
        self.tab_Pedido.setSortingEnabled(False)
        self.tab_Pedido.setWordWrap(True)
        self.tab_Pedido.setCornerButtonEnabled(True)
        self.tab_Pedido.horizontalHeader().setCascadingSectionResizes(False)
        self.tab_Pedido.horizontalHeader().setDefaultSectionSize(150)
        self.tab_Pedido.horizontalHeader().setProperty("showSortIndicator", True)
        self.tab_Pedido.horizontalHeader().setStretchLastSection(False)
        self.tab_Pedido.verticalHeader().setCascadingSectionResizes(False)
        self.tab_Pedido.verticalHeader().setStretchLastSection(False)
        self.mostralall = QPushButton(self.tab_32)
        self.mostralall.setObjectName(u"mostralall")
        self.mostralall.setGeometry(QRect(330, 380, 101, 31))
        self.tabWidget.addTab(self.tab_32, "")
        self.tabPedidos.addTab(self.tab_17, "")
        self.tab_8 = QWidget()
        self.tab_8.setObjectName(u"tab_8")
        self.verticalLayout = QVBoxLayout(self.tab_8)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.label_31 = QLabel(self.tab_8)
        self.label_31.setObjectName(u"label_31")

        self.verticalLayout.addWidget(self.label_31)

        self.nombre = QLineEdit(self.tab_8)
        self.nombre.setObjectName(u"nombre")

        self.verticalLayout.addWidget(self.nombre)

        self.label_47 = QLabel(self.tab_8)
        self.label_47.setObjectName(u"label_47")

        self.verticalLayout.addWidget(self.label_47)

        self.rfc = QLineEdit(self.tab_8)
        self.rfc.setObjectName(u"rfc")

        self.verticalLayout.addWidget(self.rfc)

        self.label_48 = QLabel(self.tab_8)
        self.label_48.setObjectName(u"label_48")

        self.verticalLayout.addWidget(self.label_48)

        self.rf = QLineEdit(self.tab_8)
        self.rf.setObjectName(u"rf")

        self.verticalLayout.addWidget(self.rf)

        self.label_49 = QLabel(self.tab_8)
        self.label_49.setObjectName(u"label_49")

        self.verticalLayout.addWidget(self.label_49)

        self.df = QLineEdit(self.tab_8)
        self.df.setObjectName(u"df")

        self.verticalLayout.addWidget(self.df)

        self.label_50 = QLabel(self.tab_8)
        self.label_50.setObjectName(u"label_50")

        self.verticalLayout.addWidget(self.label_50)

        self.concepto = QLineEdit(self.tab_8)
        self.concepto.setObjectName(u"concepto")
        self.concepto.setReadOnly(True)

        self.verticalLayout.addWidget(self.concepto)

        self.label_51 = QLabel(self.tab_8)
        self.label_51.setObjectName(u"label_51")

        self.verticalLayout.addWidget(self.label_51)

        self.id_orden = QLineEdit(self.tab_8)
        self.id_orden.setObjectName(u"id_orden")

        self.verticalLayout.addWidget(self.id_orden)

        self.pushButton_11 = QPushButton(self.tab_8)
        self.pushButton_11.setObjectName(u"pushButton_11")

        self.verticalLayout.addWidget(self.pushButton_11)

        self.pushButton_5 = QPushButton(self.tab_8)
        self.pushButton_5.setObjectName(u"pushButton_5")

        self.verticalLayout.addWidget(self.pushButton_5)

        self.pushButton_12 = QPushButton(self.tab_8)
        self.pushButton_12.setObjectName(u"pushButton_12")

        self.verticalLayout.addWidget(self.pushButton_12)

        self.tabPedidos.addTab(self.tab_8, "")

        self.retranslateUi(Dialog)

        self.tabPedidos.setCurrentIndex(3)
        self.EditarEmpleado.setCurrentIndex(0)
        self.Mostrar.setCurrentIndex(2)
        self.AgregarEmpleado_3.setCurrentIndex(2)
        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        self.label_2.setText(QCoreApplication.translate("Dialog", u"Nombre Empleado", None))
        self.label_4.setText(QCoreApplication.translate("Dialog", u"Roll", None))
        self.label_5.setText(QCoreApplication.translate("Dialog", u"CURP", None))
        self.label_6.setText(QCoreApplication.translate("Dialog", u"RFC", None))
        self.label_7.setText(QCoreApplication.translate("Dialog", u"Direccion", None))
        self.label_8.setText(QCoreApplication.translate("Dialog", u"Telefono", None))
        self.pushButton.setText(QCoreApplication.translate("Dialog", u"Agregar", None))
        self.pushButton_2.setText(QCoreApplication.translate("Dialog", u"Cancelar", None))
        self.label_36.setText("")
        self.EditarEmpleado.setTabText(self.EditarEmpleado.indexOf(self.tab_3), QCoreApplication.translate("Dialog", u"Agregar", None))
        self.mostrar_all_empleados.setText(QCoreApplication.translate("Dialog", u"Mostrar todos", None))
        ___qtablewidgetitem = self.tableEmpleado.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("Dialog", u"ID Empleado", None));
        ___qtablewidgetitem1 = self.tableEmpleado.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("Dialog", u"Nombre", None));
        ___qtablewidgetitem2 = self.tableEmpleado.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("Dialog", u"Roll", None));
        ___qtablewidgetitem3 = self.tableEmpleado.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("Dialog", u"CURP", None));
        ___qtablewidgetitem4 = self.tableEmpleado.horizontalHeaderItem(4)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("Dialog", u"RFC", None));
        ___qtablewidgetitem5 = self.tableEmpleado.horizontalHeaderItem(5)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("Dialog", u"Domicilio", None));
        ___qtablewidgetitem6 = self.tableEmpleado.horizontalHeaderItem(6)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("Dialog", u"Telefono", None));
        self.EditarEmpleado.setTabText(self.EditarEmpleado.indexOf(self.tab_10), QCoreApplication.translate("Dialog", u"Mostrar", None))
        self.label_3.setText(QCoreApplication.translate("Dialog", u"ID Empleado", None))
        self.label_9.setText(QCoreApplication.translate("Dialog", u"Nombre Empleado", None))
        self.label_10.setText(QCoreApplication.translate("Dialog", u"Roll", None))
        self.label_11.setText(QCoreApplication.translate("Dialog", u"CURP", None))
        self.label_12.setText(QCoreApplication.translate("Dialog", u"RFC", None))
        self.label_13.setText(QCoreApplication.translate("Dialog", u"Domicilio", None))
        self.label_14.setText(QCoreApplication.translate("Dialog", u"Telefono", None))
        self.mostrar_edit.setText(QCoreApplication.translate("Dialog", u"Mostrar Empleado", None))
        self.ActualizarEmp.setText(QCoreApplication.translate("Dialog", u"Actualizar", None))
        self.pushbutton_EliminarEm.setText(QCoreApplication.translate("Dialog", u"Eliminar Empleado", None))
        self.label_37.setText("")
        self.EditarEmpleado.setTabText(self.EditarEmpleado.indexOf(self.tab_4), QCoreApplication.translate("Dialog", u"Editar", None))
        self.tabPedidos.setTabText(self.tabPedidos.indexOf(self.tab), QCoreApplication.translate("Dialog", u"Empleados", None))
        self.label_16.setText(QCoreApplication.translate("Dialog", u"Nombre Proveedor", None))
        self.label_17.setText(QCoreApplication.translate("Dialog", u"Telefono Proveedor", None))
        self.label_20.setText(QCoreApplication.translate("Dialog", u"Direccion", None))
        self.agregar_prov.setText(QCoreApplication.translate("Dialog", u"Agregar", None))
        self.pushButton_6.setText(QCoreApplication.translate("Dialog", u"Cancelar", None))
        self.label_35.setText("")
        self.Mostrar.setTabText(self.Mostrar.indexOf(self.tab_12), QCoreApplication.translate("Dialog", u"Agregar", None))
        self.mostrar_all_prov_3.setText(QCoreApplication.translate("Dialog", u"Mostrar todos", None))
        ___qtablewidgetitem7 = self.Mostrar_table_prov.horizontalHeaderItem(0)
        ___qtablewidgetitem7.setText(QCoreApplication.translate("Dialog", u"Id provedoor", None));
        ___qtablewidgetitem8 = self.Mostrar_table_prov.horizontalHeaderItem(1)
        ___qtablewidgetitem8.setText(QCoreApplication.translate("Dialog", u"Nombre", None));
        ___qtablewidgetitem9 = self.Mostrar_table_prov.horizontalHeaderItem(2)
        ___qtablewidgetitem9.setText(QCoreApplication.translate("Dialog", u"Telefono", None));
        ___qtablewidgetitem10 = self.Mostrar_table_prov.horizontalHeaderItem(3)
        ___qtablewidgetitem10.setText(QCoreApplication.translate("Dialog", u"Direccion", None));
        self.Mostrar.setTabText(self.Mostrar.indexOf(self.tab_13), QCoreApplication.translate("Dialog", u"Mostrar", None))
        self.label_18.setText(QCoreApplication.translate("Dialog", u"ID Proveedor", None))
        self.mostrar_prov.setText(QCoreApplication.translate("Dialog", u"Mostrar Proveedor", None))
        self.actualizar_prov.setText(QCoreApplication.translate("Dialog", u"Actualizar", None))
        self.eliminar_prov.setText(QCoreApplication.translate("Dialog", u"Eliminar", None))
        self.label_19.setText(QCoreApplication.translate("Dialog", u"Nombre", None))
        self.label_21.setText(QCoreApplication.translate("Dialog", u"Telefono", None))
        self.label_25.setText(QCoreApplication.translate("Dialog", u"Direccion", None))
        self.label_38.setText("")
        self.Mostrar.setTabText(self.Mostrar.indexOf(self.tab_11), QCoreApplication.translate("Dialog", u"Editar", None))
        self.tabPedidos.setTabText(self.tabPedidos.indexOf(self.tab_2), QCoreApplication.translate("Dialog", u"Proveedores", None))
        self.label_23.setText(QCoreApplication.translate("Dialog", u"Nombre Ingrediente", None))
        self.label_24.setText(QCoreApplication.translate("Dialog", u"Id Proovedor", None))
        self.label_28.setText(QCoreApplication.translate("Dialog", u"Cantidad Ing", None))
        self.add_ing.setText(QCoreApplication.translate("Dialog", u"Agregar", None))
        self.pushButton_8.setText(QCoreApplication.translate("Dialog", u"Cancelar", None))
        self.label_39.setText("")
        ___qtablewidgetitem11 = self.Mostrar_table_prov_3.horizontalHeaderItem(0)
        ___qtablewidgetitem11.setText(QCoreApplication.translate("Dialog", u"Id provedoor", None));
        ___qtablewidgetitem12 = self.Mostrar_table_prov_3.horizontalHeaderItem(1)
        ___qtablewidgetitem12.setText(QCoreApplication.translate("Dialog", u"Nombre", None));
        self.AgregarEmpleado_3.setTabText(self.AgregarEmpleado_3.indexOf(self.tab_14), QCoreApplication.translate("Dialog", u"Agregar", None))
        self.mostrar_all_Ing_4.setText(QCoreApplication.translate("Dialog", u"Mostrar todos", None))
        ___qtablewidgetitem13 = self.tabl_Ing.horizontalHeaderItem(0)
        ___qtablewidgetitem13.setText(QCoreApplication.translate("Dialog", u"ID Ingredientes", None));
        ___qtablewidgetitem14 = self.tabl_Ing.horizontalHeaderItem(1)
        ___qtablewidgetitem14.setText(QCoreApplication.translate("Dialog", u"Nombre", None));
        ___qtablewidgetitem15 = self.tabl_Ing.horizontalHeaderItem(2)
        ___qtablewidgetitem15.setText(QCoreApplication.translate("Dialog", u"ID proveedor", None));
        ___qtablewidgetitem16 = self.tabl_Ing.horizontalHeaderItem(3)
        ___qtablewidgetitem16.setText(QCoreApplication.translate("Dialog", u"Cantidad", None));
        self.AgregarEmpleado_3.setTabText(self.AgregarEmpleado_3.indexOf(self.tab_15), QCoreApplication.translate("Dialog", u"Mostrar", None))
        self.label_26.setText(QCoreApplication.translate("Dialog", u"ID ingrediente", None))
        self.label_27.setText(QCoreApplication.translate("Dialog", u"Nombre", None))
        self.mostrar_ing_edit.setText(QCoreApplication.translate("Dialog", u"Mostrar Ingrediente", None))
        self.eliminar_ing_edit.setText(QCoreApplication.translate("Dialog", u"Eliminar", None))
        self.actualizar_ing_edit.setText(QCoreApplication.translate("Dialog", u"Actualizar", None))
        self.label_29.setText(QCoreApplication.translate("Dialog", u"Cantidad", None))
        self.label_30.setText(QCoreApplication.translate("Dialog", u"ID prov", None))
        self.label_40.setText("")
        self.AgregarEmpleado_3.setTabText(self.AgregarEmpleado_3.indexOf(self.tab_16), QCoreApplication.translate("Dialog", u"Editar", None))
        self.tabPedidos.setTabText(self.tabPedidos.indexOf(self.tab_5), QCoreApplication.translate("Dialog", u"Ingredientes", None))
        self.label_45.setText("")
        self.pushButton_7.setText(QCoreApplication.translate("Dialog", u"Crear Orden", None))
        self.pushButton_9.setText(QCoreApplication.translate("Dialog", u"Mostrar Ordenes", None))
        self.label_94.setText(QCoreApplication.translate("Dialog", u"Id empleado", None))
        self.label_95.setText(QCoreApplication.translate("Dialog", u"Numero de mesa", None))
        self.label_15.setText("")
        self.label_96.setText(QCoreApplication.translate("Dialog", u"Fecha", None))
        self.label_97.setText(QCoreApplication.translate("Dialog", u"ID Orden", None))
        self.tabPedidos.setTabText(self.tabPedidos.indexOf(self.tab_9), QCoreApplication.translate("Dialog", u"Orden", None))
        ___qtablewidgetitem17 = self.table_menu.horizontalHeaderItem(0)
        ___qtablewidgetitem17.setText(QCoreApplication.translate("Dialog", u"ID Producto", None));
        ___qtablewidgetitem18 = self.table_menu.horizontalHeaderItem(1)
        ___qtablewidgetitem18.setText(QCoreApplication.translate("Dialog", u"Nombre", None));
        ___qtablewidgetitem19 = self.table_menu.horizontalHeaderItem(2)
        ___qtablewidgetitem19.setText(QCoreApplication.translate("Dialog", u"Descripcion", None));
        ___qtablewidgetitem20 = self.table_menu.horizontalHeaderItem(3)
        ___qtablewidgetitem20.setText(QCoreApplication.translate("Dialog", u"Precio", None));
        self.pushButton_4.setText(QCoreApplication.translate("Dialog", u"Mostrar Pizzas", None))
        self.label_42.setText(QCoreApplication.translate("Dialog", u"Nombre producto", None))
        self.label_43.setText(QCoreApplication.translate("Dialog", u"Descripcion", None))
        self.label_44.setText(QCoreApplication.translate("Dialog", u"Precio", None))
        self.Crear_receta.setText(QCoreApplication.translate("Dialog", u"Crear Receta", None))
        self.Crear_receta_2.setText(QCoreApplication.translate("Dialog", u"Editar Receta", None))
        self.Crear_receta_3.setText(QCoreApplication.translate("Dialog", u"Editar Producto", None))
        self.tabPedidos.setTabText(self.tabPedidos.indexOf(self.tab_7), QCoreApplication.translate("Dialog", u"Productos", None))
        self.label_32.setText(QCoreApplication.translate("Dialog", u"Fecha pedido", None))
        self.label_33.setText(QCoreApplication.translate("Dialog", u"ID Proveedor", None))
        self.crear_P.setText(QCoreApplication.translate("Dialog", u"Crear pedido", None))
        self.label_34.setText(QCoreApplication.translate("Dialog", u"ID empleado", None))
        self.label_41.setText("")
        self.pushButton_3.setText(QCoreApplication.translate("Dialog", u"Mostrar Proveedores", None))
        ___qtablewidgetitem21 = self.Mostrar_table_prov_2.horizontalHeaderItem(0)
        ___qtablewidgetitem21.setText(QCoreApplication.translate("Dialog", u"Id provedoor", None));
        ___qtablewidgetitem22 = self.Mostrar_table_prov_2.horizontalHeaderItem(1)
        ___qtablewidgetitem22.setText(QCoreApplication.translate("Dialog", u"Nombre", None));
        self.label.setText("")
        self.label_46.setText(QCoreApplication.translate("Dialog", u"ID Pedido", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_18), QCoreApplication.translate("Dialog", u"Alta Pedido", None))
        self.MostrarPedido_button.setText(QCoreApplication.translate("Dialog", u"Mostrar pedido", None))
        self.label_67.setText(QCoreApplication.translate("Dialog", u"ID Pedido", None))
        ___qtablewidgetitem23 = self.tab_Pedido.horizontalHeaderItem(0)
        ___qtablewidgetitem23.setText(QCoreApplication.translate("Dialog", u"Fecha", None));
        ___qtablewidgetitem24 = self.tab_Pedido.horizontalHeaderItem(1)
        ___qtablewidgetitem24.setText(QCoreApplication.translate("Dialog", u"Proveedor", None));
        ___qtablewidgetitem25 = self.tab_Pedido.horizontalHeaderItem(2)
        ___qtablewidgetitem25.setText(QCoreApplication.translate("Dialog", u"Empleado", None));
        ___qtablewidgetitem26 = self.tab_Pedido.horizontalHeaderItem(3)
        ___qtablewidgetitem26.setText(QCoreApplication.translate("Dialog", u"Ingrediente", None));
        ___qtablewidgetitem27 = self.tab_Pedido.horizontalHeaderItem(4)
        ___qtablewidgetitem27.setText(QCoreApplication.translate("Dialog", u"Cantidad", None));
        self.mostralall.setText(QCoreApplication.translate("Dialog", u"Mostrar todos", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_32), QCoreApplication.translate("Dialog", u"Mostrar Pedido", None))
        self.tabPedidos.setTabText(self.tabPedidos.indexOf(self.tab_17), QCoreApplication.translate("Dialog", u"Pedido", None))
        self.label_31.setText(QCoreApplication.translate("Dialog", u"Nombre", None))
        self.label_47.setText(QCoreApplication.translate("Dialog", u"RFC", None))
        self.label_48.setText(QCoreApplication.translate("Dialog", u"Regimen Fiscal", None))
        self.label_49.setText(QCoreApplication.translate("Dialog", u"Direccion fiscal", None))
        self.label_50.setText(QCoreApplication.translate("Dialog", u"Concepto", None))
        self.concepto.setText(QCoreApplication.translate("Dialog", u"Consumo", None))
        self.label_51.setText(QCoreApplication.translate("Dialog", u"ID Orden", None))
        self.pushButton_11.setText(QCoreApplication.translate("Dialog", u"Agregar", None))
        self.pushButton_5.setText(QCoreApplication.translate("Dialog", u"Mostrar Facturas", None))
        self.pushButton_12.setText(QCoreApplication.translate("Dialog", u"Cancelar", None))
        self.tabPedidos.setTabText(self.tabPedidos.indexOf(self.tab_8), QCoreApplication.translate("Dialog", u"Facturacion", None))
    # retranslateUi

